name: GNTRun
main: tntrun.guitarkrabpom
softdepend: [WorldEdit, Vault]
version: 3.2.dev
author: _GuitarKrabPom_
commands:
  tntrunsetup:
    description: GNTRun arena setup commands
    aliases: gntsetup
    usage: Unknown command
  tntrun:
    description: GNTRun game commands
    aliases: gnt
    usage: Use /gnt help to show all commands available in plugin
  tntrunconsole:
    description: GNTRun console commands
    aliases: gntconsole
    usage: Unknown command
